version: "3"

services:
  graphviz-webapp:
    image: ${DOCKER_REGISTRY:-registry.gitlab.com/rajiff}/graphviz-webapp:1.0.0
    build: ./graphviz-webapp/
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 256M
      restart_policy:
        condition: always
    ports:
      - "3000:3000"
    env_file: "./docker_env/${NODE_ENV}/webapp-${NODE_ENV:-local}.env"

  graphviz-webservice:
    image: ${DOCKER_REGISTRY:-registry.gitlab.com/rajiff}/graphviz-webservice:1.0.0
    build: ./graphviz-webservice/
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 256M
      restart_policy:
        condition: always
    ports:
      - "8080:8080"
    env_file: "./docker_env/${NODE_ENV}/webservice-${NODE_ENV:-local}.env"

  graphviz-neo4j:
    image: neo4j:4.0
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 256M
      restart_policy:
        condition: always
    # volumes:
    #   - ./neo4j/data:/data
    #   - ./neo4j/import:/var/lib/neo4j/import
    #   - ./neo4j/plugins:/plugins
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/test
